---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java 
    tag: "8"

params:
  MOVIE_FUN_URL: https://moviefun-strangest-crossrail.apps.cumuluslabs.io

inputs:
- name: moviefun-source

run:
  path: moviefun-source/ci/tasks/smoke-test.sh
